version: '3'

services:
    web:
        container_name: requi_api
        restart: always
        build: .
        ports:
            - "8000:8000"
        links:
            - mongodb
        volumes:
            - /usr/src/app/node_modules
            - .:/usr/src/app
    mongodb: 
        container_name: db-requisiciones
        image: mongo
        ports:
            - "27017:27017"
        logging:
            driver: none