version: '3'

services:
    web:
        container_name: requi_api
        depends_on: db-requisiciones
        restart: always
        build: .
        ports:
            - "8000:8000"
        expose: "8000"
        links:
            - db-requisiciones
        volumes:
            - /usr/src/app/node_modules
            - .:/usr/src/app
    db-requisiciones: 
        container_name: db-requisiciones
        image: mongo
        ports:
            - "27017:27017"
        expose: "27017"
        logging:
            driver: none